DROP FUNCTION IF EXISTS employeeData.has_access;

DELIMITER //
CREATE FUNCTION has_access(empid INT) RETURNS BOOLEAN
SQL SECURITY INVOKER
DETERMINISTIC
READS SQL DATA
BEGIN
	IF CURRENT_ROLE() LIKE '%admin_role%' THEN
		RETURN TRUE;
	ELSEIF empid = @session_empid THEN
		RETURN TRUE;
	END IF;
	
	RETURN FALSE;
END //
DELIMITER ;